# Generated by Django 5.2.5 on 2025-08-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current analysis status', max_length=20),
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('tables_found', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='analyzer.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('table_index', models.PositiveIntegerField(help_text='Index of table on the page')),
                ('bounding_box', models.JSONField(help_text='Coordinates of the table bounding box')),
                ('table_data', models.JSONField(help_text='Structured table data as JSON')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score from the detection model', null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_tables', to='analyzer.analysisresult')),
            ],
            options={
                'ordering': ['page_number', 'table_index'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='extractedtable',
            unique_together={('analysis_result', 'page_number', 'table_index')},
        ),
    ]